name: Build Docker Images

on: 
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build docker images
      run: ./build-images.sh
