name: Build BamToolkit SDK Docker Image W/ Tests

on: 
  push:
    branches:
      - bamtoolkit

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build bamtoolkit w/ SDK docker image
      run: ./build-image.sh bamtoolkit-sdk
    - name: commit 'ci-test' branch
      run: ./ci-commit-test.sh
