name: Build BamToolkit SDK Docker Image and Trigger Tests

on: 
  push:
    branches:
      - bamtoolkit

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
    steps:
    - uses: actions/checkout@v1
    - name: build bamtoolkit w/ SDK docker image
      run: ./build-image.sh bamtoolkit-sdk
    - name: commit 'ci-test' branch
      run: ./ci-commit-test.sh
