name: Build BamToolkit

on: 
  push:
    branches:
      - bamtoolkit

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build bamtoolkit w/ SDK docker image
      run: ./build-image.sh bamtoolkit-sdk
    - name: buld bamtoolkit test docker image
      run: ./build-image.sh bamtoolkit-sdk-tests
