name: Build BamToolkit SDK Docker Image and Trigger Tests

on: 
  push:
    branches:
      - bamtoolkit

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '2.2.402'
    - name: set ssh keys
      run: ./set-keys.sh
    - name: install toolkit
      run: source ./setup.sh
    - name: build docker image
      run: ./build-image.sh bamtoolkit-sdk
    - name: commit 'ci-test' branch
      run: ./ci-commit-test.sh
